/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6678",
            customMemoryMap:
           [          
                ["L2SRAM", 
                     {
                        name: "L2SRAM",
                        base: 0x00800000,                    
                        len: 0x00080000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMCSRAM", 
                     {
                        name: "MSMCSRAM",
                        base: 0x0c020000,                    
                        len: 0x003E0000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3", 
                     {
                        name: "DDR3",
                        base: 0x80000000,                    
                        len: 0x04000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMCSRAM_NC_PHY", 
                     {
                        name: "MSMCSRAM_NC_PHY",
                        base: 0x0C000000,                    
                        len: 0x00020000,                    
                        space: "code/data",
                        access: "RW",
                     }
                ],
                ["MSMCSRAM_NC_VIRT", 
                     {
                        name: "MSMCSRAM_NC_VIRT",
                        base: 0xA0000000,                    
                        len: 0x00020000,                    
                        space: "code/data",
                        access: "RW",
                     }
                ],
           ],
          l1DMode: "32k",
          l1PMode: "32k",
          l2Mode: "0k",

    });
    
instance :
    
    override config string codeMemory  = "MSMCSRAM";   
    override config string dataMemory  = "DDR3";                                
    override config string stackMemory = "L2SRAM";

    config String l1DMode = "32k";
    config String l1PMode = "32k";
    config String l2Mode = "0k";
}
